<h2>Listado de Trabajos</h2>
<hr>
<div class="row">
	<div class="primary col-md-8 col-sm-12 col-xs-12">
<?php
	if($trabajos) { 
		foreach($trabajos as $t) { 
			$link = 
				$this->url(
					'trabajos/trabajo-detalle', array('action'=>'detalle', 'id' => $t->getTr_codigo())
				);
?>			
			<div class="item row">
			<a class="col-md-4 col-sm-4 col-xs-12" href="<?=$link ?>">
			<img class="img-responsive project-image" src="<?= $t->getTr_imagen_perfil() ?>" alt="project name">
			</a>
			<div class="desc col-md-8 col-sm-8 col-xs-12">
			<h3 class="title"><a href="<?=$link ?>"><?=$t->getTr_titulo()?></a></h3>
			<p><?= $ayudaService->cortar_frase($t->getTr_cuerpo(), 20) ?></p>
			<p><a class="more-link" href="<?=$link ?>"><i class="fa fa-external-link"></i> Ver Detalle</a></p>
			</div><!--//desc-->                          
			</div><!--//item-->
		<?php 
		}
	}
		?>
	</div>
</div>