<aside class="languages aside section">
<div class="section-inner">
<h2 class="heading">Lenguajes</h2>
<div class="content">
<ul class="list-unstyled">
<li class="item">
<span class="title"><strong>Español:</strong></span>
<span class="level">Nativo <br><br class="visible-xs"><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </span>
</li><!--//item-->
<li class="item">
<span class="title"><strong>Ingles:</strong></span>
<span class="level">Competencia profesional<br><br class="visible-sm visible-xs"><i class="fa fa-star"></i> <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></span>
</li><!--//item-->
</ul>
</div><!--//content-->
</div><!--//section-inner-->
</aside>