	<div class="primary col-md-8 col-sm-12 col-xs-12">
		<section class="about section">
		<div class="section-inner">
		<h2 class="heading">Bienvenido!</h2>
		<div class="content">
		<p>Gracias por interesarte en mi trabajo.</p>
		<p>Aquí podrás conocer mis aplicaciones, experiencias laborales, habilidades, conocimientos técnicos y
			estudios, asi como mis intereses fuera del mundo informático, para que así puedas formarte una idea mas completa
			sobre mí perfil laboral</p>
			<p>Tambien podras revisar el detalle de mis trabajos incluyendo codigo fuente
			desde mi Github</p>
		
		
		<!--Ingeniero ejecución en computación e informática del Instituto 
		Profesional Virginio Gómez,  con más de 2 años de experiencia 
		en análisis y programación de sitios web, aplicaciones para dispositivos 
		móviles Android (Java). 
		He trabajado en dos empresas de software Aeurus y Genesys (PHP).--></p>
		</div><!--//content-->
		</div><!--//section-inner-->                 
		</section><!--//section-->
		<?= $this->partial('partial/habilidades.phtml'); ?> 
	</div>
	<div class="secondary col-md-4 col-sm-12 col-xs-12">
		<?= $this->partial('partial/info.phtml'); ?> 
		<?= $this->partial('partial/educacion.phtml'); ?> 
		<?= $this->partial('partial/idiomas.phtml'); ?> 
	</div>


