<!-- ******HEADER****** --> 
<header class="header">
		<div class="container">                       
				<img class="profile-image img-responsive pull-left" src="imagenes/sitio/yo.jpg" alt="Francisco Rene Flores Fuentes" width="90px" />
				<div class="profile-content pull-left">
						<h1 class="name">Francisco Rene Flores Fuentes</h1>
						<h2 class="desc">Web App Developer</h2>   
						<ul class="social list-inline">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>                   
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>                   
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-github-alt"></i></a></li>                 
						</ul> 
				</div><!--//profile-->
		</div><!--//container-->
</header><!--//header-->

<div class="row">
	<div class="primary col-md-8 col-sm-12 col-xs-12">
		<section class="about section">
		<div class="section-inner">
		<h2 class="heading">Sobre Mí</h2>
		<div class="content">
		<p>Write a brief intro about yourself. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.</p>    

		<p>It's a good idea to include your personal interests and hobbies as well. Commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
		<p><a class="more-link" href="#"><i class="fa fa-external-link"></i> Ver más</a></p> 
		</div><!--//content-->
		</div><!--//section-inner-->                 
		</section><!--//section-->
	</div>
	<div class="secondary col-md-4 col-sm-12 col-xs-12">
		<aside class="skills aside section">
			<div class="section-inner">
			<h2 class="heading">Habilidades</h2>
			<div class="content">
				<p class="intro"></p>

				<div class="skillset">

				<div class="item">
				<h3 class="level-title">PHP<span class="level-label" data-toggle="tooltip" data-placement="left" data-animation="true" title="" data-original-title="You can use the tooltip to add more info...">Expert</span></h3>
				<div class="level-bar">
				<div class="level-bar-inner" data-level="96%" style="width: 96%;">
				</div>                                      
				</div><!--//level-bar-->                                 
				</div><!--//item-->

				<div class="item">
				<h3 class="level-title">Javascript &amp; jQuery<span class="level-label" data-original-title="" title="">Expert</span></h3>
				<div class="level-bar">
				<div class="level-bar-inner" data-level="96%" style="width: 96%;">
				</div>                                      
				</div><!--//level-bar-->                                 
				</div><!--//item-->

				<div class="item">
				<h3 class="level-title">HTML5, CSS3, SASS &amp; LESS<span class="level-label" data-original-title="" title="">Expert</span></h3>
				<div class="level-bar">
				<div class="level-bar-inner" data-level="96%" style="width: 96%;">
				</div>                                      
				</div><!--//level-bar-->                                 
				</div><!--//item-->

				<div class="item">
				<h3 class="level-title">Ruby on Rails<span class="level-label" data-original-title="" title="">Pro</span></h3>
				<div class="level-bar">
				<div class="level-bar-inner" data-level="85%" style="width: 85%;">
				</div>                                      
				</div><!--//level-bar-->                                 
				</div><!--//item-->

				<p><a class="more-link" href="#"><i class="fa fa-external-link"></i> Ver más</a></p> 
				</div>              
				</div><!--//content-->  
			</div><!--//section-inner-->                 
		</aside><!--//section-->
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<h1 class="page-header">Trabajos</h2>
	</div>
</div>
<div class="row">
	<div class="col-sm-6 col-md-4">
		<div class="thumbnail">
			<img src="/imagenes/modulos/inicio/carousel/codeigniter.jpg" alt="...">
			<div class="caption">
				<h3>Thumbnail label</h3>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			</div>
			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>				
		</div>		
	</div>
	<div class="col-sm-6 col-md-4">
		<div class="thumbnail">
			<img src="/imagenes/modulos/inicio/carousel/codeigniter.jpg" alt="...">
			<div class="caption">
				<h3>Thumbnail label</h3>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			</div>
			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>				
		</div>		
	</div>
	<div class="col-sm-6 col-md-4">
		<div class="thumbnail">
			<img src="/imagenes/modulos/inicio/carousel/codeigniter.jpg" alt="...">
			<div class="caption">
				<h3>Thumbnail label</h3>
				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			</div>
			<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>				
		</div>		
	</div>
	<p><a class="more-link pull-right" href="#"><i class="fa fa-external-link"></i> Ver más</a></p> 	
</div>