<aside class="education aside section">
	<div class="section-inner">
		<h2 class="heading">Educación</h2>
		<div class="content">
			<div class="item">                      
			<h3 class="title"><i class="fa fa-graduation-cap"></i>Ingeniería de Ejecución en Computación e Informática</h3>
			<h4 class="university">Instituto Profesional Virginio Gómez <span class="year">(2010-2013)</span></h4>
			</div>
			<div class="item">                      
			<h3 class="title"><i class="fa fa-graduation-cap"></i>Curso Responsive Web Design Fundamentals</h3>
			<h4 class="university">Udacity <span class="year">(2017, enero)</span></h4>
			</div>
		</div><!--//content-->		
	</div><!--//section-inner-->
</aside>
