<footer class="footer">
<div class="container text-center">
<small class="copyright">
Creado con 
<i class="fa fa-heart"></i> por 
<a href="http://themes.3rdwavemedia.com" target="_blank">
Francisco Flores
</a> 
<br>
Este sitio esta desarrollado usando 
<a href="https://framework.zend.com/" class="zend">MVC Skeleton Application</a> 
y corre sobre PHP 5.2
<br>
Diseño de
<a href="http://themes.3rdwavemedia.com" target="_blank">
Xiaoying Riley</a> for developers
</small>
</div><!--//container-->
</footer>
