<header class="header">
		<div class="container">                       
				<img class="profile-image img-circle img-responsive pull-left" src="imagenes/sitio/yo.jpg" alt="Francisco Rene Flores Fuentes" width="180px" />
				<div class="profile-content pull-left">
						<h1 class="name">Francisco Flores</h1>
						<h2 class="desc">Desarrollador de Software</h2>   
						<ul class="social list-inline">
								<li><a href="https://www.facebook.com/franciscorenef"><i class="fa fa-facebook"></i></a></li>                   
								<!--<li><a href="#"><i class="fa fa-twitter"></i></a></li>-->                   
								<!--<li><a href="#"><i class="fa fa-google-plus"></i></a></li>-->
								<li><a href="https://www.linkedin.com/in/franciscofloresfuentes/"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="https://github.com/FranciscoRene"><i class="fa fa-github-alt"></i></a></li>                 
						</ul> 
				</div><!--//profile-->
				<a class="btn btn-cta-primary pull-right" href="/contacto" target="_blank"><i class="fa fa-paper-plane"></i>Contacto</a>              
		</div><!--//container-->
</header><!--//header-->