<aside class="info aside section">
<div class="section-inner">
<h2 class="heading sr-only">Información Básica</h2>
<div class="content">
<ul class="list-unstyled">
<li><i class="fa fa-map-marker"></i><span class="sr-only">Residencia:</span>Talcahuano, Chile</li>
<li><i class="fa fa-envelope-o"></i><span class="sr-only">Email:</span><a href="#">franciscorenef@gmail.com</a></li>
<li><i class="fa fa-phone"></i><span class="sr-only">Phone:</span><a href="#">950792873</a></li>
</ul>
</div><!--//content-->  
</div><!--//section-inner-->                 
</aside>